### ISSUE TITLE
invoke init on super class mixins

### ISSUE THREAD

**Issue by dredzone** [WebReflection/universal-mixin#4]
when class A extends B, and class B (super) has mixins decorators, calling init() in constructor of A  doesn't invoke init methods of mixins from class B (super).

**Comment by WebReflection** [comment]
that's because `init` is an override so, like any other override, you should `super.init()` ... right?

**Comment by dredzone** [comment]
```javascript
@EventedMixin
class A {
  constructor() {
    this.init();
  }
}

@TestMixin
class B extends A {
  constructor() {
   super.init()
  }
}
```

if @EventedMixin and @TestMixin mixin have init methods super.init() of B instance will not call @EventedMixin init() method, if I remove @TestMixin from B then init of @EventedMixin is triggered.

**Comment by WebReflection** [comment]
You are right. Calling `super` for a mixin is probably also wrong and `init` should simply initialize whatever is needed.

The version `1.1.0` should fix this and provide the following scenario:

```js
@EventedMixin
class A {
  constructor() {
    this.init();
  }
}

@TestMixin
class B extends A {
  constructor() {
   this.init();
  }
}
```

The `init` method will take care of initializing mixins in the assignment/enrichement order (inherited first then)

Please close this if you think now everything works as expected, thanks.

**Comment by dredzone** [comment]
working as expected, thanks for quick fix.

**Comment by dredzone** [comment]
after the change IE11 Windows7 throws Unable to get property 'slice' of undefined on proto[uid].slice(0)

```
value: uid in proto && proto[uid] ? proto[uid].slice(0) : []
```
photo[uid] check fixes the problem.

**Comment by WebReflection** [comment]
Please open a new bug for IE11, thanks
