### ISSUE TITLE
IE11 Windows7 throws Unable to get property 'slice' of undefined on proto[uid].slice(0)

### ISSUE THREAD

**Issue by dredzone** [WebReflection/universal-mixin#5]
IE11 Windows7 throws Unable to get property 'slice' of undefined on proto[uid].slice(0)

```
value: uid in proto && proto[uid] ? proto[uid].slice(0) : []
```

photo[uid] check fixes the problem.

**Comment by WebReflection** [comment]
It kinda doesn't . If uid is there it must be an Array. If not there's
something else very bad going on. Will have a look

**Comment by WebReflection** [comment]
can you please test this page?
http://webreflection.github.io/universal-mixin/test/

I don't have any error in there ... I need a concrete example that fails on IE11 but not on other browsers, thanks.

**Comment by WebReflection** [comment]
Actually, I'd like to know if you are using any polyfill upfront. I think something is messing with `Symbol` , creating them on the `Object.prototype` so that `in` check always finds them.

I'll try to work around this but please let me know, thanks.
